// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { SessionModelUpdateSource } from "./SessionModelUpdateSource";

export type ThreadModelUpdatedNotification = { threadId: string, previousModel: string, model: string, previousReasoningEffort: ReasoningEffort | null, reasoningEffort: ReasoningEffort | null, source: SessionModelUpdateSource, currentTurnKeepsPreviousModelAndReasoning: boolean, };
